{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: paisa-bank-app-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "paisa-bank-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: {{ .Values.secrets.mongoRootUsername | quote }}
  MONGO_ROOT_PASSWORD: {{ .Values.secrets.mongoRootPassword | quote }}
  JWT_SECRET:          {{ .Values.secrets.jwtSecret | quote }}
  MONGODB_URI:         {{ include "paisa-bank-app.mongoUri" . | quote }}
{{- end }}
