name: Docker CI/CD

on: workflow_dispatch

env:
  REGISTRY: docker.io
  IMAGE_NAME_FRONTEND: ${{ secrets.DOCKER_USERNAME }}/frontend-paisa-app
  IMAGE_NAME_BACKEND: ${{ secrets.DOCKER_USERNAME }}/backend-paisa-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: 📥 Checkout the latest code
        uses: actions/checkout@v4

      # Set short SHA
      - name: 🔑 Set short SHA
        run: |
             echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Docker login
      - name: 🔐 Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # =========================
      # FRONTEND IMAGE
      # =========================
      - name: 🏗️ Build Frontend Image
        run: |
          docker build -t $IMAGE_NAME_FRONTEND:latest \
                 -t $IMAGE_NAME_FRONTEND:$SHORT_SHA \
                 -f frontend/Dockerfile frontend

      - name: 📤 Push Frontend Image
        run: |
          docker push $IMAGE_NAME_FRONTEND:latest
          docker push $IMAGE_NAME_FRONTEND:$SHORT_SHA

      # =========================
      # BACKEND IMAGE
      # =========================
      - name: 🏗️ Build Backend Image
        run: |
          docker build -t $IMAGE_NAME_BACKEND:latest \
                       -t $IMAGE_NAME_BACKEND:$SHORT_SHA \
                       -f backend/Dockerfile backend
                      

      - name: 📤 Push Backend Image
        run: |
          docker push $IMAGE_NAME_BACKEND:latest
          docker push $IMAGE_NAME_BACKEND:$SHORT_SHA

      # =========================
      # OUTPUT INFO
      # =========================
      - name: 📢 Output Image Info
        run: |
          echo "Frontend Image:"
          echo "$IMAGE_NAME_FRONTEND:latest"
          echo "$IMAGE_NAME_FRONTEND:$SHORT_SHA"

          echo "Backend Image:"
          echo "$IMAGE_NAME_BACKEND:latest"
          echo "$IMAGE_NAME_BACKEND:$SHORT_SHA"
